# Generated by Django 3.1.2 on 2020-10-19 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.postcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
