# Generated by Django 3.1.2 on 2020-10-19 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("source_url", models.URLField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.postcategory",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.post"
                    ),
                ),
                ("tags", models.ManyToManyField(to="content.Tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
