# Generated by Django 3.1.5 on 2021-01-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210102_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='content.post'),
        ),
        migrations.AlterField(
            model_name='video',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.post'),
        ),
    ]
