# Generated by Django 3.1.5 on 2021-01-24 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_auto_20210120_2115"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="category",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="search_count",
        ),
        migrations.RemoveField(
            model_name="video",
            name="category",
        ),
        migrations.RemoveField(
            model_name="video",
            name="search_count",
        ),
        migrations.AddField(
            model_name="postcategory",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tag",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="title",
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="title",
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name="video",
            name="content",
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name="video",
            name="length",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=280),
        ),
        migrations.CreateModel(
            name="TwitterTrendingTopic",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=280)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("trends_position", models.IntegerField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_topics",
                        to="content.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
