# Generated by Django 3.1.3 on 2020-11-23 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tag_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('length', models.IntegerField()),
                ('content', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.postcategory')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('tags', models.ManyToManyField(to='news.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
